(define (problem strips-gripper)
   (:domain gripper-domain)
   (:objects rooma roomb roomc roomd roome roomf roomg ball1 ball2 ball3 ball4 ball5 ball6 ball7
             ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 left right)
   (:init (room rooma)
          (room roomb)
          (room roomc)
          (room roomd)
          (room roome)
          (room roomf)
          (room roomg)
		  
          (ball ball1)
          (ball ball2)
          (ball ball3)
          (ball ball4)
          (ball ball5)
          (ball ball6)
          (ball ball7)
          (ball ball8)
          (ball ball9)
          (ball ball10)
          (ball ball11)
          (ball ball12)
          (ball ball13)
          (ball ball14)
          (ball ball15)
		  
          (gripper left)
          (gripper right)
          (at-robby roomb)
          (free left)
          (free right)
		  
          (at ball1 rooma)
          (at ball2 roomb)
          (at ball3 roomc)
          (at ball4 roomd)
          (at ball5 roomf)
          (at ball6 roomd)
          (at ball7 roomc)
          (at ball8 roomg)
          (at ball9 rooma)
          (at ball10 roomb)
          (at ball11 roomc)
          (at ball12 roomd)
          (at ball13 roome)
          (at ball14 roomd)
		  (at ball15 rooma))
		  
   (:goal (and (at ball1 rooma)
               (at ball2 rooma)
               (at ball3 roomb)
               (at ball4 roomb)
               (at ball5 roomc)
               (at ball6 roomc)
               (at ball7 roomd)
               (at ball8 roomd)
               (at ball9 roome)
               (at ball10 roome)
               (at ball11 roomf)
               (at ball12 roomf)
               (at ball13 roomg)
               (at ball14 roomg)
			   (at ball15 roomg))))
